[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
jupyterlab = "4.3.5"
plotly = "6.0.0"
dash = "2.18.2"
shifter-pandas = "1.0.3"
pandas = "2.2.3"
statsmodels = "0.14.4"
jupyter-dash = "0.4.2"
jupyter-core = "5.7.2"
certifi = "2024.8.30"
flask = "3.0.3"
tornado = "6.4.2"
requests = "2.32.3"
urllib3 = "2.2.3"
jupyter-server = "2.14.2"
jinja2 = "3.1.5"
idna = "3.10"

[tool.ruff]
target-version = "py310"
line-length = 110

[tool.ruff.lint.pydocstyle]
convention = "numpy"
